import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Intro from "@/components/Sections/Intro";
import SectionRenderer from "@/components/SectionRenderer";
import { useUserContext } from "@/context/builderContext";
import { SectionSpacer } from "@/styles/atoms/Layout";
import styled from "styled-components";
import AddSection from "@/components/AddSection/AddSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { builderConfig } = useUserContext();

  return (
    <>
      <Head>
        <title>Portfolio | Builder </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Intro />
        <SectionWrapper>
          <LeftSpace></LeftSpace>
          <Sections>
            <AddSection />
            {builderConfig?.sections?.map((section) => {
              return (
                <>
                  <SectionRenderer {...section} key={section.sectionKey} />
                  <SectionSpacer />
                </>
              );
            })}
          </Sections>
        </SectionWrapper>
      </main>
    </>
  );
}

//styles

const SectionWrapper = styled.section`
  display: flex;
  width: 100%;
  height: 100vh;
`;

const LeftSpace = styled.div`
  width: 50%;
  height: 100%;
  background-color: green;
`;

const Sections = styled.div`
  width: 50%;
  height: 100%;
`;
